import {defineField, defineType} from 'sanity'

export const speaker = defineType({
  name: 'speaker',
  title: 'Speaker',
  type: 'document',
  groups: [
    {name: 'profile', title: 'Profile', default: true},
    {name: 'social', title: 'Social'},
    {name: 'import', title: 'Import'},
  ],
  fields: [
    defineField({
      name: 'event',
      title: 'Event',
      type: 'reference',
      to: [{type: 'event'}],
      validation: (rule) => rule.required(),
      group: 'profile',
    }),
    defineField({
      name: 'name',
      title: 'Name',
      type: 'string',
      validation: (rule) => rule.required(),
      group: 'profile',
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: {source: 'name', maxLength: 96},
      validation: (rule) => rule.required(),
      description: 'Stable key for n8n upserts (e.g. jenna-ritten).',
      group: 'profile',
    }),
    defineField({
      name: 'headshot',
      title: 'Headshot',
      type: 'image',
      options: {hotspot: true},
      validation: (rule) => rule.required(),
      group: 'profile',
    }),
    defineField({
      name: 'bio',
      title: 'Bio',
      type: 'text',
      rows: 6,
      validation: (rule) => rule.required(),
      group: 'profile',
    }),
    defineField({
      name: 'organization',
      title: 'Organization',
      type: 'string',
      validation: (rule) => rule.required(),
      group: 'profile',
    }),
    defineField({
      name: 'position',
      title: 'Position',
      type: 'string',
      validation: (rule) => rule.required(),
      group: 'profile',
    }),
    defineField({
      name: 'isWTM',
      title: 'Women Techmakers Ambassador',
      type: 'boolean',
      initialValue: false,
      group: 'profile',
    }),
    defineField({
      name: 'isGDE',
      title: 'Google Developer Expert',
      type: 'boolean',
      initialValue: false,
      group: 'profile',
    }),
    defineField({
      name: 'featuredSession',
      title: 'Featured session',
      type: 'reference',
      to: [{type: 'session'}],
      description:
        'Session shown on the speaker grid card. If empty, the site uses the first session in import order.',
      group: 'profile',
    }),
    defineField({
      name: 'published',
      title: 'Published',
      type: 'boolean',
      initialValue: true,
      description: 'Unpublish to hide this speaker without deleting the document.',
      group: 'profile',
    }),
    defineField({
      name: 'email',
      title: 'Email',
      type: 'string',
      group: 'social',
      description: 'Organizer use only — exclude from public site queries.',
    }),
    defineField({
      name: 'linkedIn',
      title: 'LinkedIn URL',
      type: 'url',
      group: 'social',
    }),
    defineField({
      name: 'twitter',
      title: 'Twitter handle',
      type: 'string',
      group: 'social',
    }),
    defineField({
      name: 'github',
      title: 'GitHub',
      type: 'string',
      group: 'social',
    }),
    defineField({
      name: 'instagram',
      title: 'Instagram',
      type: 'string',
      group: 'social',
    }),
    defineField({
      name: 'mastodon',
      title: 'Mastodon URL',
      type: 'url',
      group: 'social',
    }),
    defineField({
      name: 'website',
      title: 'Website',
      type: 'url',
      group: 'social',
    }),
    defineField({
      name: 'importKey',
      title: 'Import key',
      type: 'string',
      readOnly: true,
      group: 'import',
      description: 'Optional row identifier from the runner sheet.',
    }),
    defineField({
      name: 'headshotFilename',
      title: 'Headshot filename',
      type: 'string',
      group: 'import',
      description: 'Drive filename used on last import (e.g. JennaRitten.jpg).',
    }),
  ],
  preview: {
    select: {
      title: 'name',
      subtitle: 'organization',
      media: 'headshot',
      year: 'event.year',
    },
    prepare: ({title, subtitle, media, year}) => ({
      title: title ?? 'Unnamed speaker',
      subtitle: [year, subtitle].filter(Boolean).join(' · '),
      media,
    }),
  },
})
